version: '3.8'

services:
  backend:
    image: tagtest:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:80
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433